- id: doi:10.1101/2021.07.05.450786
  image: images/articles/phenoplier.png
  description: Here we introduce the PhenoPLIER framework, an omnigenic approach that integrates genetic studies (GWAS/TWAS) with gene modules learned from expression data. PhenoPLIER provides 1) a regression framework that computes an association between gene modules and diseases, 2) a clustering approach that finds groups of diseases with shared transcriptomic properties, and 3) a gene module-based drug-repurposing method.
- id: doi:10.1101/2022.06.15.496326
  image: images/articles/ccc.png
  description: This article introduces the Clustermatch Correlation Coefficient (CCC), an efficient, easy-to-use and not-only-linear coefficient based on machine learning models. CCC can detect biologically meaningful linear and nonlinear patterns missed by standard, linear-only correlation coefficients.
- id: doi:10.1101/2023.01.21.525030
  image: images/articles/manubot-ai-editor.png
  description: We developed the Manubot AI Editor, a plugin to the Manubot publishing infrastructure that uses manuscript section-specific prompts and OpenAI's models (such as GPT-3) to automatically revise and improve the text.
- id: doi:10.1016/S2213-2600(19)30055-4
  image: images/articles/asthma.png
- id: doi:10.1038/s41467-022-33628-8
  image: images/articles/asthma_endotypes.png
- id: doi:10.1101/2020.11.12.373647
  image: images/articles/prs.png
- id: doi:10.1126/sciadv.aba2083
  image: images/articles/phenomexcan.png
- id: doi:10.1101/2020.07.01.182097
  image: images/articles/prob_coloc.png
- id: doi:10.1093/bioinformatics/btaa111
  image: images/articles/dl4papers.png
- id: doi:10.1093/bioinformatics/bty925
  image: images/articles/ukbrest.png
- id: doi:10.1101/814350
  image: images/articles/exploiting.png
- id: pmid:29800232
  image: images/articles/predicting-mirna.png
- id: doi:10.1093/bioinformatics/bty899
  image: images/articles/clustermatch.png
- id: doi:10.1371/journal.pgen.1007889
  image: images/articles/multixcan.png
- id: doi:10.1016/j.ins.2016.04.027
  image: images/articles/divcontrol.png
- id: doi:10.1093/bib/bbv054
  image: images/articles/webdemo-builder.png
- id: doi:10.1093/bib/bby037
  hide: "true"
- id: doi:10.1101/292649
  hide: "true"
- id: pmid:30357313
  hide: "true"
- id: doi:10.1038/s43588-023-00488-1
  image: images/articles/high-dim-diseases.png
