- id: doi:10.1101/2021.07.05.450786
  image: https://raw.githubusercontent.com/pivlab/pivlab.org/main/images/articles/phenoplier.png
  description: Here we introduce the PhenoPLIER framework, an omnigenic approach that integrates genetic studies (GWAS/TWAS) with gene modules learned from expression data. PhenoPLIER provides 1) a regression framework that computes an association between gene modules and diseases, 2) a clustering approach that finds groups of diseases with shared transcriptomic properties, and 3) a gene module-based drug-repurposing method.
- id: doi:10.1101/2022.06.15.496326
  image: https://raw.githubusercontent.com/pivlab/pivlab.org/main/images/articles/ccc.png
  description: This article introduces the Clustermatch Correlation Coefficient (CCC).
- id: doi:10.1101/2023.01.21.525030
  image: https://raw.githubusercontent.com/pivlab/pivlab.org/main/images/articles/manubot-ai-editor.png
  description: We developed the Manubot AI Editor, a plugin to the Manubot publishing infrastructure that uses manuscript section-specific prompts and OpenAI's models (such as GPT-3) to automatically revise and improve the text.
